version: '3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_container
    network_mode: host
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    network_mode: host
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
